### ISSUE TITLE
Responsive SVG image support

### ISSUE THREAD

**Issue by akuma** [bitjourney/plantuml-service#25]
The SVG image maybe not display all.

e.g.
![2018-01-17 4 08 59](https://user-images.githubusercontent.com/237677/35032236-29e65ab4-fba1-11e7-94d6-f4a02f0d0d64.png)

**Comment by gfx** [comment]
More details?

**Comment by gfx** [comment]
SVG is resizable. Can you try CSS to responsive, e.g. `width: 100%` ?

**Comment by akuma** [comment]
It works. 👍
