### ISSUE TITLE
update to plantuml latest

### ISSUE THREAD

**Issue by c835722** [bitjourney/plantuml-service#35]
Hi,
Thank you for your software. I use it prolifically with vscode jebbs plantuml plugin via its plantuml.render setting.

When I preview the following document
```
@startuml
version
@enduml
```
I notice the version is 1.2018.3

Is there a way to redirect the plantuml-service to call a local version of the plantuml jar so as to pick up an updated version of the base plantuml.jar?

Cheers.

**Comment by gfx** [comment]
Know the current version refers PlantUML v1.2018.8. Thanks to ping me!

**Comment by c835722** [comment]
The brew packaged version is v1.31 whereas the latest release (that supports that most recent PlanUML version) is v1.32.
How does the brew packaged version get updated to v.1.32 so users who install via brew can benefit?

**Comment by gfx** [comment]
Oh, you use brew version, right?

Just updated https://github.com/bitjourney/homebrew-self and you can use it now.
