### ISSUE TITLE
Links in svg not working

### ISSUE THREAD

**Issue by mattbishop** [bitjourney/plantuml-service#43]
I recent regression around link target in plantuml has been fixed in the 1.2019 version:

http://forum.plantuml.net/8572/svglinktarget-not-working

Could you please upgrade the plantuml jar?

**Comment by kuroponzu** [comment]
PlantUmlVersion in v1.4.0 is 1.2022.5.
So, prease use it.

https://github.com/bitjourney/plantuml-service/releases/tag/v1.4.0
