### ISSUE TITLE
Can not pull from docker hub

### ISSUE THREAD

**Issue by nielinjie** [bitjourney/plantuml-service#46]
I can not pull from docker hub, any one have the same problem?
> Error response from daemon: manifest for bitjourney/plantuml-service:latest not found

**Comment by nielinjie** [comment]
When I add tag (current is '1.3.5') explicitly, it works. So please update document, which says `docker pull bitjourney/plantuml-service` without version tag.

**Comment by kuroponzu** [comment]
Update readme!

```
docker pull bitjourney/plantuml-service:1.4.0
```
